# FL scenario
m: 1000 # number of the clients
T: 200 # number of the rounds
alg: fedavg # fedavg fedprox moon
case: 1 # four NE cases

# dataset
dataset: cifar10 # mnist or cifar10 or imdb or femnist
subset: 1 # use a subset of the whole dataset
data_train: 40000 # training subset size
data_val: 10000 # validation subset size (taken from training set)
data_test: 10000 # test subset size
noniid: 2 # number of classes per client for non-iid setting, 0 means iid

# model
model: cnn # neural network
activation: relu # relu or sigmoid
loss: cn # mse or cn

# server side parameters
frac: 0.1 # proportion of the active clients per round

# client side parameters
optimizer: sgd # sgd or adam
bs: 20 # batch size, false means FGD
lr: 0.05 # learning rate
w_decay: 1.0e-4 # weight decay

mu: 0.1 # proximal term weight for FedProx
moon_mu: 0.1 # contrastive loss weight for MOON

# Transformer parameters
max_length: 256
emb_dim: 128
nhead: 2
nhid: 128
nlayers: 2

# Other parameters
save_freq: 1 # callback
device: mps # cuda or cpu or mps
plot: 1 # plot or not
seed: 77
tag: FL # name tag for logging
T0: 0 # start round, if not 1, continue from the checkpoint

