# Trial scenario
seed: 77
tag: FL_Game # tag for saving 

# FL-Game scenario
m: 20 # number of clients
T: 50 # number of rounds
lamda: [0, 5, 0.05] # reward factor range

# parameters of the player
data_vol: [500, 500] # range of the data size of clients
alpha: [1, 2] # range of the running cost factor alpha_i
reso_q: [1, 1] # range of the minimal efforts of clients
reso_Q: [20, 30] # range of the resources of clients
reso_distri: uniform # normal or uniform

# parameters of the best-response algorithm
solver: analytic
stop_e: 1.0e-10
stop_iter: 1000

